#!/bin/bash
# ============================================================
# init-secrets.sh - Generate secrets for VOC Auto Bot
# ============================================================
# Usage:
#   ./scripts/init-secrets.sh          # Generate if not exists
#   ./scripts/init-secrets.sh --force   # Regenerate all secrets
#
# Generates:
#   - .env file (for docker-compose standalone)
#   - secrets/*.txt files (for Docker Swarm / production)
#
# Prerequisites: openssl (available on macOS/Linux)
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
SECRETS_DIR="$PROJECT_ROOT/secrets"

FORCE=false
if [ "${1:-}" = "--force" ]; then
    FORCE=true
fi

# Check if .env already exists (unless --force)
if [ "$FORCE" = false ] && [ -f "$ENV_FILE" ]; then
    echo "[INFO] .env file already exists at: $ENV_FILE"
    echo "  Use --force to regenerate: ./scripts/init-secrets.sh --force"
    exit 0
fi

# Create secrets directory
mkdir -p "$SECRETS_DIR"

# ============================================================
# Generate random secrets
# ============================================================
POSTGRES_PASSWORD=$(openssl rand -base64 24)
REDIS_PASSWORD=$(openssl rand -base64 24)
MINIO_ROOT_PASSWORD=$(openssl rand -base64 24)
JWT_SECRET=$(openssl rand -base64 48)
AI_SERVICE_API_KEY=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)

# ============================================================
# Write .env file (docker-compose standalone)
# ============================================================
cat > "$ENV_FILE" <<EOF
# =========================
# VOC Auto Bot - Environment Variables
# =========================
# Generated by scripts/init-secrets.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# WARNING: This file contains secrets. Never commit to version control.

# =========================
# Database Configuration
# =========================
POSTGRES_DB=vocautobot
POSTGRES_USER=voc_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PORT=5432

# =========================
# Redis Configuration
# =========================
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}

# =========================
# MinIO Configuration
# =========================
MINIO_ROOT_USER=minio_admin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# =========================
# JWT Configuration
# =========================
JWT_SECRET=${JWT_SECRET}

# =========================
# AI Service Configuration
# =========================
AI_SERVICE_API_KEY=${AI_SERVICE_API_KEY}

# =========================
# Encryption Configuration
# =========================
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# =========================
# Application Configuration
# =========================
SPRING_PROFILES_ACTIVE=docker

# =========================
# LLM Configuration
# =========================
LLM_MODEL=gpt-oss:20b

# =========================
# Application Ports
# =========================
BACKEND_PORT=8080
FRONTEND_PORT=3000

# =========================
# Frontend Configuration
# =========================
NEXT_PUBLIC_API_URL=http://localhost:8080/api
EOF

echo "[OK] .env created at: $ENV_FILE"

# ============================================================
# Write secrets/*.txt files (Docker Swarm / production)
# ============================================================
printf '%s' "$JWT_SECRET" > "$SECRETS_DIR/jwt_secret.txt"
printf '%s' "$POSTGRES_PASSWORD" > "$SECRETS_DIR/db_password.txt"
printf '%s' "$REDIS_PASSWORD" > "$SECRETS_DIR/redis_password.txt"
printf '%s' "$MINIO_ROOT_PASSWORD" > "$SECRETS_DIR/minio_root_password.txt"
printf '%s' "$AI_SERVICE_API_KEY" > "$SECRETS_DIR/ai_service_api_key.txt"
printf '%s' "$ENCRYPTION_KEY" > "$SECRETS_DIR/encryption_key.txt"

# Set restrictive permissions on secret files
chmod 600 "$SECRETS_DIR"/*.txt

echo "[OK] Secret files created in: $SECRETS_DIR/"
echo ""
echo "Generated secrets:"
echo "  - jwt_secret.txt (64 chars, base64)"
echo "  - db_password.txt (24 bytes, base64)"
echo "  - redis_password.txt (24 bytes, base64)"
echo "  - minio_root_password.txt (24 bytes, base64)"
echo "  - ai_service_api_key.txt (32 bytes, hex)"
echo "  - encryption_key.txt (32 bytes, hex)"
echo ""
echo "To start services: docker compose up -d"
